import { useEffect, useState, type FormEvent } from "react";
import { mapFamilyMember } from "../contracts/mappers";
import type { FamilyMember } from "../models/domain";
import { services } from "../services";

const formatMoney = (amount: number) => new Intl.NumberFormat("en-MY", { style: "currency", currency: "MYR" }).format(amount);

export function Family() {
  const [items, setItems] = useState<FamilyMember[]>([]); const [adding, setAdding] = useState(false); const [transfer, setTransfer] = useState<FamilyMember | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ full_name: "", ic: "", relationship: "" }); const [amount, setAmount] = useState(""); const [pin, setPin] = useState("");
  const load = () => services.family.listFamilyMembers().then((rows) => setItems(rows.map(mapFamilyMember))).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load Family Members."));
  useEffect(() => { void load(); }, []);
  const add = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { await services.family.createFamilyMember({ ...form, idempotency_key: crypto.randomUUID() }); setForm({ full_name: "", ic: "", relationship: "" }); setAdding(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to add Family Member."); } finally { setBusy(false); } };
  const send = async (event: FormEvent) => { event.preventDefault(); if (!transfer) return; setBusy(true); setError(""); try { await services.wallet.transferToFamilyMember(transfer.id, Number(amount), pin, crypto.randomUUID()); setPin(""); setAmount(""); setTransfer(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to transfer."); } finally { setBusy(false); } };
  return <div className="page-wrap"><header className="page-header compact-header"><div><p className="eyebrow">Managed profiles</p><h1>Family Members</h1><p>Manage assisted profiles and transfer funds from your main wallet.</p></div><button className="button primary" onClick={() => setAdding(true)}>Add Family Member</button></header>{error && <div className="form-error" role="alert">{error}</div>}<div className="member-grid">{items.map((member) => <article className="card member-card" key={member.id}><div className="member-avatar large">{member.fullName.split(" ").map((part) => part[0]).slice(0, 2).join("")}</div><div><p className="eyebrow">{member.relationship}</p><h2>{member.fullName}</h2><span>{member.icNumberMasked}</span></div><dl><div><dt>Wallet balance</dt><dd>{formatMoney(member.wallet.availableBalance)}</dd></div><div><dt>Enrolment</dt><dd>{member.enrolmentStatus.replaceAll("_", " ")}</dd></div></dl><button className="button secondary full" onClick={() => setTransfer(member)} disabled={member.enrolmentStatus !== "ENROLMENT_COMPLETED"}>Transfer money</button></article>)}</div>{adding && <div className="modal-backdrop" role="presentation"><form className="modal-card" onSubmit={add}><div className="section-heading"><div><p className="eyebrow">Managed profile</p><h2>Add Family Member</h2></div><button className="link-button" type="button" onClick={() => setAdding(false)}>Close</button></div><p>This profile receives no independent login, password, PIN, or direct top-up.</p><label>Full legal name<input value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} required /></label><label>IC number<input value={form.ic} onChange={(e) => setForm({ ...form, ic: e.target.value })} required /></label><label>Relationship<input value={form.relationship} onChange={(e) => setForm({ ...form, relationship: e.target.value })} required /></label><button className="button primary full" disabled={busy}>Create provisional profile</button></form></div>}{transfer && <div className="modal-backdrop"><form className="modal-card" onSubmit={send}><div className="section-heading"><div><p className="eyebrow">PIN-authorized transfer</p><h2>Transfer to {transfer.fullName}</h2></div><button className="link-button" type="button" onClick={() => { setTransfer(null); setPin(""); }}>Close</button></div><label>Amount in MYR<input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} required /></label><label>Main account PIN<input type="password" inputMode="numeric" maxLength={6} value={pin} onChange={(e) => setPin(e.target.value.replace(/\D/g, ""))} required /></label><button className="button primary full" disabled={busy}>Confirm transfer</button></form></div>}</div>;
}
